- hosts: localhost
  become: true
  tasks:
  - name: Install Apache
    ansible.builtin.apt:
      name: apache2
      update_cache: true # Add this to ensure package cache is updated

  - name: Start and enable apache2 service
    ansible.builtin.service:
      name: apache2
      state: started
      enabled: true # Ensure the service starts on boot

  - name: Copy index.html
    ansible.builtin.copy:
      src: index.html
      dest: /var/www/html/index.html
      mode: '0644' # Set appropriate file permissions
